version: "3.8"

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    hostname: kafka-ui
    networks:
      - hadoop
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=hadoop-master:9092,hadoop-master:9093,hadoop-master:9094
      - KAFKA_CLUSTERS_0_ZOOKEEPER=hadoop-master:2181

networks:
  hadoop:
    external: true
    driver: bridge
