version: '3.8'

services:
  hadoop-master:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "9870:9870"   # NameNode Web UI
      - "8088:8088"   # ResourceManager Web UI
      - "7077:7077"   # Spark Master
      - "19888:19888" # JobHistory Server
      - "8080:8080"   # Spark Master Web UI
      - "9000:9000"   # NameNode RPC
    volumes:
      - ${USERPROFILE}/Documents/hadoop_project:/shared_volume
    networks:
      - hadoop-network
    stdin_open: true
    tty: true

  hadoop-slave1:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    ports:
      - "8040:8042"   # NodeManager Web UI
    networks:
      - hadoop-network
    stdin_open: true
    tty: true
    depends_on:
      - hadoop-master

  hadoop-slave2:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    ports:
      - "8041:8042"   # NodeManager Web UI
    networks:
      - hadoop-network
    stdin_open: true
    tty: true
    depends_on:
      - hadoop-master

networks:
  hadoop-network:
    driver: bridge